AllCops:
  TargetRubyVersion: 2.3

# Lines must be 100 chars or less, default 80.
Metrics/LineLength:
  Max: 100

# Allow variable assignment in combination with 'if' and 'case' statements.
Lint/EndAlignment:
  AlignWith: variable

# Disable check on magic comment to freeze literal string.
Style/FrozenStringLiteralComment:
  Enabled: false

# Use nested modules and classes instead of the multiline style.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Ensures that the assignment operator and the rhs are on separate lines
# for the set of supported types.
Style/MultilineAssignmentLayout:
  SupportedTypes:
    - block
    - case
    - class
    - if
    - kwbegin
    - module
  EnforcedStyle: same_line
